# Generated by Django 2.1.7 on 2019-04-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_product_name', models.CharField(max_length=100)),
                ('image_product_image', models.ImageField(blank=True, upload_to='static/main/images')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_product_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
