# Generated by Django 2.1.7 on 2019-04-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='static/main/imagesPage')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='static/main/imagesProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcatalog',
            name='fk_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatalog', to='main.Catalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='fk_subcatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.Subcatalog'),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='main.Product'),
        ),
        migrations.AddField(
            model_name='countproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_product', to='main.Product'),
        ),
        migrations.AddField(
            model_name='countproduct',
            name='fk_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_size', to='main.SizeProduct'),
        ),
    ]
