# Generated by Django 2.1.7 on 2019-04-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190421_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='main.Product'),
        ),
        migrations.AlterField(
            model_name='countproduct',
            name='fk_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='main.SizeProduct'),
        ),
        migrations.AlterField(
            model_name='imagepage',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagesPage'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_products', to='main.Product'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagesProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fk_subcatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Subcatalog'),
        ),
        migrations.AlterField(
            model_name='sizeproduct',
            name='size',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcatalog',
            name='fk_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatalogs', to='main.Catalog'),
        ),
    ]
