# Generated by Django 2.1.7 on 2019-04-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('catalogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['fk_size'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='imagesProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('fk_subcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Subcatalog')),
            ],
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_products', to='catalogApp.Product'),
        ),
        migrations.AddField(
            model_name='countproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='catalogApp.Product'),
        ),
        migrations.AddField(
            model_name='countproduct',
            name='fk_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='catalogApp.SizeProduct'),
        ),
    ]
