# Generated by Django 2.1.7 on 2019-05-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0002_auto_20190425_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_product', to='catalogApp.Product'),
        ),
    ]
