# Generated by Django 2.1.7 on 2019-05-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_auto_20190517_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='old_price',
        ),
    ]
