# Generated by Django 2.1.7 on 2019-05-08 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogApp', '0003_auto_20190508_2042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('finish', models.BooleanField(default=False)),
                ('sum', models.PositiveIntegerField(blank=True)),
                ('fk_client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('size', models.IntegerField(blank=True)),
                ('fk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='orderApp.Order')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='catalogApp.Product')),
            ],
        ),
    ]
