# Generated by Django 2.1.7 on 2019-05-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productApp', '0007_auto_20190518_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('surname', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('comment', models.TextField(blank=True)),
                ('delivery_price', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('size', models.IntegerField()),
                ('fk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='orderApp.Order')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='productApp.Product')),
            ],
        ),
    ]
