# Generated by Django 2.1.7 on 2019-05-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_auto_20190515_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
